// GET ALL ALBUM
export const GET_ALBUM = "GET_ALBUM";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILED = "GET_ALBUM_FAILED";

// CREATE ALBUM ALBUM
export const CREATE_ALBUM = "CREATE_ALBUM";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAILED = "CREATE_ALBUM_FAILED";

// RESET FLAG PHOTO
export const RESET_FLAG_PHOTO = "RESET_FLAG_PHOTO";
